ALTER TABLE timer ALTER COLUMN started_time TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE timer ALTER COLUMN time_created TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE timer ALTER COLUMN duration TYPE INTERVAL HOUR TO SECOND;
